create table public.product_images (
    id bigint generated by default as identity primary key,
    product_id bigint not null references public.products(id) on delete cascade,
    storage_path text not null,
    alt_text text,
    sort_order integer not null default 0,
    is_primary boolean not null default false,
    created_at timestamptz not null default now()
);


-- =========================================
-- 6. Profiles
-- =========================================

create table public.profiles (
    id uuid primary key references auth.users(id) on delete cascade,
    full_name text,
    phone text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);


-- =========================================
-- 7. Carts
-- =========================================

create table public.carts (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),

    constraint carts_user_unique unique (user_id)
);


-- =========================================
-- 8. Cart Items
-- =========================================

create table public.cart_items (
    id bigint generated by default as identity primary key,
    cart_id bigint not null references public.carts(id) on delete cascade,
    product_variant_id bigint not null references public.product_variants(id) on delete cascade,
    quantity integer not null default 1,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),

    constraint cart_items_quantity_check
        check (quantity > 0),

    constraint cart_items_unique_variant
        unique (cart_id, product_variant_id)
);


-- =========================================
-- 9. Orders
-- =========================================

create table public.orders (
    id bigint generated by default as identity primary key,
    user_id uuid references auth.users(id) on delete set null,

    status text not null default 'pending',

    subtotal numeric(12,2) not null default 0,
    shipping numeric(12,2) not null default 0,
    tax numeric(12,2) not null default 0,
    discount numeric(12,2) not null default 0,
    total numeric(12,2) not null default 0,

    currency text not null default 'IRR',

    shipping_name text not null,
    shipping_phone text not null,
    shipping_address text not null,

    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),

    constraint orders_status_check
        check (
            status in (
                'pending',
                'paid',
                'processing',
                'shipped',
                'completed',
                'cancelled',
                'refunded'
            )
        )
);


-- =========================================
-- 10. Order Items
-- =========================================

create table public.order_items (
    id bigint generated by default as identity primary key,
    order_id bigint not null references public.orders(id) on delete cascade,

    product_variant_id bigint references public.product_variants(id) on delete set null,

    product_name text not null,
    sku text,

    quantity integer not null,
    unit_price numeric(12,2) not null,
    total_price numeric(12,2) not null,

    created_at timestamptz not null default now(),

    constraint order_items_quantity_check
        check (quantity > 0)
);


-- =========================================
-- 11. Promo Codes
-- =========================================

create table public.promo_codes (
    id bigint generated by default as identity primary key,

    code text not null unique,

    discount_type text not null,
    discount_value numeric(12,2) not null,

    minimum_order numeric(12,2) not null default 0,

    max_uses integer,
    used_count integer not null default 0,

    starts_at timestamptz,
    expires_at timestamptz,

    is_active boolean not null default true,

    created_at timestamptz not null default now(),

    constraint promo_discount_type_check
        check (discount_type in ('percentage', 'fixed')),

    constraint promo_discount_value_check
        check (discount_value >= 0),

    constraint promo_minimum_order_check
        check (minimum_order >= 0),

    constraint promo_used_count_check
        check (used_count >= 0)
);


-- =========================================
-- 12. Settings
-- =========================================

create table public.settings (
    id bigint generated by default as identity primary key,

    tax_rate numeric(5,2) not null default 10,
    shipping_fee numeric(12,2) not null default 0,
    free_shipping_threshold numeric(12,2),
    currency text not null default 'IRR',

    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);