SET local check_function_bodies = off;

ALTER TABLE "public"."orders"
  DROP CONSTRAINT "orders_status_check";

ALTER TABLE "public"."bands"
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."cart_items"
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."carts"
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."categories"
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."order_items"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."order_stock_reservations" (
  "id"                 bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "order_id"           bigint                   NOT NULL,
  "product_variant_id" bigint                   NOT NULL,
  "quantity"           integer                  NOT NULL,
  "status"             text                     NOT NULL DEFAULT 'reserved'::text,
  "created_at"         timestamp with time zone NOT NULL DEFAULT now(),
  "released_at"        timestamp with time zone,
  "confirmed_at"       timestamp with time zone,
  CONSTRAINT "order_stock_reservations_pkey" PRIMARY KEY (id),
  CONSTRAINT "order_stock_reservations_quantity_check" CHECK ((quantity > 0)),
  CONSTRAINT "order_stock_reservations_status_check" CHECK ((status = ANY (ARRAY['reserved'::text, 'released'::text, 'confirmed'::text])))
);

ALTER TABLE "public"."order_stock_reservations"
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."orders"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."payments" (
  "id"             bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "order_id"       bigint                   NOT NULL,
  "user_id"        uuid                     NOT NULL,
  "amount"         numeric                  NOT NULL,
  "gateway"        text                     NOT NULL DEFAULT 'unknown'::text,
  "authority"      text,
  "transaction_id" text,
  "status"         text                     NOT NULL DEFAULT 'pending'::text,
  "created_at"     timestamp with time zone NOT NULL DEFAULT now(),
  "paid_at"        timestamp with time zone,
  CONSTRAINT "payments_amount_check" CHECK ((amount >= (0)::numeric)),
  CONSTRAINT "payments_pkey" PRIMARY KEY (id),
  CONSTRAINT "payments_status_check" CHECK ((status = ANY (ARRAY['pending'::text, 'paid'::text, 'failed'::text, 'cancelled'::text, 'refunded'::text])))
);

ALTER TABLE "public"."payments"
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."product_images"
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."product_variants"
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."products"
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."profiles"
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."promo_codes"
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."settings"
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."orders"
  ADD COLUMN "payment_status" text NOT NULL DEFAULT 'unpaid'::text;

ALTER TABLE "public"."profiles"
  ADD COLUMN "role" text DEFAULT 'customer'::text;

ALTER TABLE "public"."profiles"
  ADD COLUMN "address" text;

CREATE OR REPLACE FUNCTION public.admin_update_order_status (
  p_order_id bigint,
  p_status   text
)
  RETURNS boolean
  LANGUAGE plpgsql
  SECURITY DEFINER
  SET search_path TO 'public'
  AS $function$
declare
    v_user_id uuid;
    v_role text;
begin
    v_user_id := auth.uid();

    if v_user_id is null then
        raise exception 'You must be logged in';
    end if;

    select role
    into v_role
    from public.profiles
    where id = v_user_id;

    if v_role is distinct from 'admin' then
        raise exception 'Admin access required';
    end if;

    if p_status not in (
        'pending',
        'confirmed',
        'processing',
        'shipped',
        'delivered',
        'cancelled'
    ) then
        raise exception 'Invalid order status';
    end if;

    if not exists (
        select 1
        from public.orders
        where id = p_order_id
    ) then
        raise exception 'Order not found';
    end if;

    update public.orders
    set
        status = p_status,
        updated_at = now()
    where id = p_order_id;

    return true;
end;
$function$;

CREATE OR REPLACE FUNCTION public.confirm_order_payment (
  p_payment_id bigint
)
  RETURNS boolean
  LANGUAGE plpgsql
  SECURITY DEFINER
  SET search_path TO 'public'
  AS $function$

DECLARE
    v_payment public.payments%ROWTYPE;
    v_order public.orders%ROWTYPE;
BEGIN

    SELECT *
    INTO v_payment
    FROM public.payments
    WHERE id = p_payment_id
    FOR UPDATE;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'Payment not found';
    END IF;

    SELECT *
    INTO v_order
    FROM public.orders
    WHERE id = v_payment.order_id
    FOR UPDATE;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'Order not found';
    END IF;

    IF v_payment.status = 'paid' THEN
        RETURN true;
    END IF;

    IF v_payment.status <> 'pending' THEN
        RAISE EXCEPTION 'Payment is not pending';
    END IF;

    IF v_order.payment_status = 'paid' THEN
        RAISE EXCEPTION 'Order is already paid';
    END IF;

    UPDATE public.payments
    SET
        status = 'paid',
        paid_at = now()
    WHERE id = p_payment_id;

    UPDATE public.order_stock_reservations
    SET
        status = 'confirmed',
        confirmed_at = now()
    WHERE order_id = v_payment.order_id
      AND status = 'reserved';

    UPDATE public.orders
    SET
        payment_status = 'paid',
        status = 'processing',
        updated_at = now()
    WHERE id = v_payment.order_id;

    RETURN true;

END;

$function$;

CREATE OR REPLACE FUNCTION public.create_order (
  p_shipping_name    text,
  p_shipping_phone   text,
  p_shipping_address text
)
  RETURNS bigint
  LANGUAGE plpgsql
  SECURITY DEFINER
  SET search_path TO 'public'
  AS $function$
declare
    v_user_id uuid;
    v_cart_id bigint;
    v_order_id bigint;

    v_subtotal numeric := 0;
    v_shipping numeric := 0;
    v_tax numeric := 0;
    v_discount numeric := 0;
    v_total numeric := 0;

    v_item record;
    v_unit_price numeric;
    v_item_total numeric;
begin
    -- فقط کاربر لاگین‌شده
    v_user_id := auth.uid();

    if v_user_id is null then
        raise exception 'You must be logged in';
    end if;

    -- اعتبارسنجی اطلاعات ارسال
    if trim(coalesce(p_shipping_name, '')) = '' then
        raise exception 'Shipping name is required';
    end if;

    if trim(coalesce(p_shipping_phone, '')) = '' then
        raise exception 'Shipping phone is required';
    end if;

    if trim(coalesce(p_shipping_address, '')) = '' then
        raise exception 'Shipping address is required';
    end if;

    -- پیدا کردن Cart کاربر
    select id
    into v_cart_id
    from public.carts
    where user_id = v_user_id
    order by created_at asc
    limit 1;

    if v_cart_id is null then
        raise exception 'Cart not found';
    end if;

    -- اگر Cart خالی باشد
    if not exists (
        select 1
        from public.cart_items
        where cart_id = v_cart_id
    ) then
        raise exception 'Cart is empty';
    end if;

    /*
        ثبت Order اولیه
    */
    insert into public.orders (
        user_id,
        status,
        subtotal,
        shipping,
        tax,
        discount,
        total,
        currency,
        shipping_name,
        shipping_phone,
        shipping_address
    )
    values (
        v_user_id,
        'pending',
        0,
        0,
        0,
        0,
        0,
        'IRR',
        trim(p_shipping_name),
        trim(p_shipping_phone),
        trim(p_shipping_address)
    )
    returning id into v_order_id;

    /*
        خواندن Cart و بررسی موجودی
    */
    for v_item in
        select
            ci.id,
            ci.product_variant_id,
            ci.quantity,
            pv.stock,
            pv.price,
            pv.sku,
            p.name as product_name
        from public.cart_items ci
        join public.product_variants pv
            on pv.id = ci.product_variant_id
        join public.products p
            on p.id = pv.product_id
        where ci.cart_id = v_cart_id
        for update of pv
    loop

        -- تعداد نامعتبر
        if v_item.quantity <= 0 then
            raise exception
                'Invalid quantity for product %',
                v_item.product_name;
        end if;

        -- موجودی کافی نیست
        if v_item.quantity > v_item.stock then
            raise exception
                'Not enough stock for product %. Available: %, requested: %',
                v_item.product_name,
                v_item.stock,
                v_item.quantity;
        end if;

        -- قیمت واقعی از DB
        v_unit_price := coalesce(
            v_item.price,
            0
        );

        v_item_total :=
            v_unit_price *
            v_item.quantity;

        v_subtotal :=
            v_subtotal +
            v_item_total;

        /*
            ذخیره Snapshot اطلاعات محصول داخل Order Item
        */
        insert into public.order_items (
            order_id,
            product_variant_id,
            product_name,
            sku,
            quantity,
            unit_price,
            total_price
        )
        values (
            v_order_id,
            v_item.product_variant_id,
            v_item.product_name,
            v_item.sku,
            v_item.quantity,
            v_unit_price,
            v_item_total
        );

        /*
            کاهش موجودی
        */
        update public.product_variants
        set stock = stock - v_item.quantity
        where id = v_item.product_variant_id;

    end loop;

    /*
        فعلاً Shipping و Tax صفر هستند
    */
    v_shipping := 0;
    v_tax := 0;
    v_discount := 0;

    v_total :=
        v_subtotal +
        v_shipping +
        v_tax -
        v_discount;

    /*
        بروزرسانی مبلغ Order
    */
    update public.orders
    set
        subtotal = v_subtotal,
        shipping = v_shipping,
        tax = v_tax,
        discount = v_discount,
        total = v_total,
        updated_at = now()
    where id = v_order_id;

    /*
        Cart بعد از ثبت سفارش خالی می‌شود
    */
    delete from public.cart_items
    where cart_id = v_cart_id;

    return v_order_id;
end;
$function$;

CREATE OR REPLACE FUNCTION public.create_order_from_cart (
  p_shipping_name    text,
  p_shipping_phone   text,
  p_shipping_address text,
  p_promo_code       text    DEFAULT NULL::text,
  p_shipping         numeric DEFAULT 0,
  p_tax              numeric DEFAULT 0
)
  RETURNS bigint
  LANGUAGE plpgsql
  SECURITY DEFINER
  SET search_path TO 'public'
  AS $function$

DECLARE
    v_user_id uuid;
    v_cart_id bigint;
    v_order_id bigint;

    v_subtotal numeric := 0;
    v_discount numeric := 0;
    v_total numeric := 0;

    v_promo public.promo_codes%ROWTYPE;
    v_promo_code text;

    v_item record;
    v_unit_price numeric;
    v_item_total numeric;

BEGIN

    -- =========================================================
    -- 1. Current authenticated user
    -- =========================================================

    v_user_id := auth.uid();

    IF v_user_id IS NULL THEN
        RAISE EXCEPTION 'You must be logged in';
    END IF;


    -- =========================================================
    -- 2. Validate shipping information
    -- =========================================================

    IF trim(coalesce(p_shipping_name, '')) = '' THEN
        RAISE EXCEPTION 'Shipping name is required';
    END IF;

    IF trim(coalesce(p_shipping_phone, '')) = '' THEN
        RAISE EXCEPTION 'Shipping phone is required';
    END IF;

    IF trim(coalesce(p_shipping_address, '')) = '' THEN
        RAISE EXCEPTION 'Shipping address is required';
    END IF;


    -- =========================================================
    -- 3. Validate amounts
    -- =========================================================

    IF COALESCE(p_shipping, 0) < 0
       OR COALESCE(p_tax, 0) < 0 THEN
        RAISE EXCEPTION 'Invalid order amounts';
    END IF;


    -- =========================================================
    -- 4. Find user's cart
    -- =========================================================

    SELECT id
    INTO v_cart_id
    FROM public.carts
    WHERE user_id = v_user_id
    LIMIT 1;

    IF v_cart_id IS NULL THEN
        RAISE EXCEPTION 'Cart not found';
    END IF;


    -- =========================================================
    -- 5. Make sure cart is not empty
    -- =========================================================

    IF NOT EXISTS (
        SELECT 1
        FROM public.cart_items
        WHERE cart_id = v_cart_id
    ) THEN
        RAISE EXCEPTION 'Cart is empty';
    END IF;


    -- =========================================================
    -- 6. Lock variants + calculate REAL subtotal
    -- =========================================================

    FOR v_item IN
        SELECT
            ci.id AS cart_item_id,
            ci.product_variant_id,
            ci.quantity,
            pv.stock,
            pv.price,
            pv.sku,
            p.name AS product_name,
            p.is_active
        FROM public.cart_items ci
        JOIN public.product_variants pv
            ON pv.id = ci.product_variant_id
        JOIN public.products p
            ON p.id = pv.product_id
        WHERE ci.cart_id = v_cart_id
        FOR UPDATE OF pv
    LOOP

        IF v_item.quantity <= 0 THEN
            RAISE EXCEPTION 'Invalid cart quantity';
        END IF;


        IF NOT COALESCE(v_item.is_active, false) THEN
            RAISE EXCEPTION
                'Product is no longer available: %',
                v_item.product_name;
        END IF;


        IF v_item.stock < v_item.quantity THEN
            RAISE EXCEPTION
                'Insufficient stock for product: %',
                v_item.product_name;
        END IF;


        v_unit_price :=
            COALESCE(v_item.price, 0);


        v_item_total :=
            v_unit_price * v_item.quantity;


        v_subtotal :=
            v_subtotal + v_item_total;

    END LOOP;


    -- =========================================================
    -- 7. Validate + calculate promo SERVER-SIDE
    -- =========================================================

    v_promo_code :=
        upper(
            trim(
                coalesce(
                    p_promo_code,
                    ''
                )
            )
        );


    IF v_promo_code <> '' THEN

        SELECT *
        INTO v_promo
        FROM public.promo_codes
        WHERE upper(trim(code)) = v_promo_code
        FOR UPDATE;


        IF NOT FOUND THEN
            RAISE EXCEPTION 'Invalid promo code';
        END IF;


        IF NOT v_promo.is_active THEN
            RAISE EXCEPTION 'Promo code is not active';
        END IF;


        IF v_promo.starts_at IS NOT NULL
           AND now() < v_promo.starts_at THEN
            RAISE EXCEPTION
                'Promo code is not active yet';
        END IF;


        IF v_promo.expires_at IS NOT NULL
           AND now() > v_promo.expires_at THEN
            RAISE EXCEPTION
                'Promo code has expired';
        END IF;


        IF v_promo.max_uses IS NOT NULL
           AND v_promo.used_count >= v_promo.max_uses THEN
            RAISE EXCEPTION
                'Promo code usage limit reached';
        END IF;


        IF v_subtotal < v_promo.minimum_order THEN
            RAISE EXCEPTION
                'Minimum order amount for this promo code is %',
                v_promo.minimum_order;
        END IF;


        IF lower(v_promo.discount_type) = 'percentage' THEN

            IF v_promo.discount_value < 0
               OR v_promo.discount_value > 100 THEN
                RAISE EXCEPTION
                    'Invalid percentage discount';
            END IF;


            v_discount :=
                round(
                    v_subtotal
                    * v_promo.discount_value
                    / 100
                );


        ELSIF lower(v_promo.discount_type) = 'fixed' THEN

            IF v_promo.discount_value < 0 THEN
                RAISE EXCEPTION
                    'Invalid fixed discount';
            END IF;


            v_discount :=
                v_promo.discount_value;


        ELSE

            RAISE EXCEPTION
                'Invalid promo discount type';

        END IF;


        v_discount :=
            LEAST(
                v_discount,
                v_subtotal
            );

    END IF;


    -- =========================================================
    -- 8. Calculate REAL total
    -- =========================================================

    v_total :=
        v_subtotal
        + COALESCE(p_shipping, 0)
        + COALESCE(p_tax, 0)
        - v_discount;


    IF v_total < 0 THEN
        v_total := 0;
    END IF;


    -- =========================================================
    -- 9. Create order
    -- =========================================================

    INSERT INTO public.orders (
        user_id,
        status,
        payment_status,
        subtotal,
        shipping,
        tax,
        discount,
        total,
        currency,
        shipping_name,
        shipping_phone,
        shipping_address
    )
    VALUES (
        v_user_id,
        'pending',
        'unpaid',
        v_subtotal,
        COALESCE(p_shipping, 0),
        COALESCE(p_tax, 0),
        v_discount,
        v_total,
        'IRR',
        trim(p_shipping_name),
        trim(p_shipping_phone),
        trim(p_shipping_address)
    )
    RETURNING id
    INTO v_order_id;


    -- =========================================================
    -- 10. Create order items
    --     + reserve stock
    -- =========================================================

    FOR v_item IN
        SELECT
            ci.id AS cart_item_id,
            ci.product_variant_id,
            ci.quantity,
            pv.stock,
            pv.price,
            pv.sku,
            p.name AS product_name
        FROM public.cart_items ci
        JOIN public.product_variants pv
            ON pv.id = ci.product_variant_id
        JOIN public.products p
            ON p.id = pv.product_id
        WHERE ci.cart_id = v_cart_id
        FOR UPDATE OF pv
    LOOP

        v_unit_price :=
            COALESCE(v_item.price, 0);


        v_item_total :=
            v_unit_price * v_item.quantity;


        -- ---------------------------------------------
        -- Order item
        -- ---------------------------------------------

        INSERT INTO public.order_items (
            order_id,
            product_variant_id,
            product_name,
            sku,
            quantity,
            unit_price,
            total_price
        )
        VALUES (
            v_order_id,
            v_item.product_variant_id,
            v_item.product_name,
            v_item.sku,
            v_item.quantity,
            v_unit_price,
            v_item_total
        );


        -- ---------------------------------------------
        -- Reserve stock
        -- ---------------------------------------------

        UPDATE public.product_variants
        SET stock =
            stock - v_item.quantity
        WHERE id =
            v_item.product_variant_id;


        INSERT INTO public.order_stock_reservations (
            order_id,
            product_variant_id,
            quantity,
            status
        )
        VALUES (
            v_order_id,
            v_item.product_variant_id,
            v_item.quantity,
            'reserved'
        );

    END LOOP;


    -- =========================================================
    -- 11. Increase promo usage
    -- =========================================================

    IF v_promo_code <> '' THEN

        UPDATE public.promo_codes
        SET used_count =
            used_count + 1
        WHERE id =
            v_promo.id;

    END IF;


    -- =========================================================
    -- 12. Clear cart
    -- =========================================================

    DELETE FROM public.cart_items
    WHERE cart_id = v_cart_id;


    -- =========================================================
    -- 13. Update cart timestamp
    -- =========================================================

    UPDATE public.carts
    SET updated_at = now()
    WHERE id = v_cart_id;


    -- =========================================================
    -- 14. Return order ID
    -- =========================================================

    RETURN v_order_id;

END;

$function$;

CREATE OR REPLACE FUNCTION public.create_payment (
  p_order_id bigint,
  p_gateway  text   DEFAULT 'unknown'::text
)
  RETURNS bigint
  LANGUAGE plpgsql
  SECURITY DEFINER
  SET search_path TO 'public'
  AS $function$

DECLARE
    v_user_id uuid;
    v_order public.orders%ROWTYPE;
    v_payment_id bigint;
    v_gateway text;
BEGIN

    -- =========================================================
    -- 1. Current authenticated user
    -- =========================================================

    v_user_id := auth.uid();

    IF v_user_id IS NULL THEN
        RAISE EXCEPTION 'You must be logged in';
    END IF;


    -- =========================================================
    -- 2. Validate gateway
    -- =========================================================

    v_gateway := lower(trim(coalesce(p_gateway, '')));

    IF v_gateway = '' THEN
        v_gateway := 'unknown';
    END IF;


    -- =========================================================
    -- 3. Get user's order
    -- =========================================================

    SELECT *
    INTO v_order
    FROM public.orders
    WHERE id = p_order_id
      AND user_id = v_user_id
    FOR UPDATE;


    IF NOT FOUND THEN
        RAISE EXCEPTION 'Order not found';
    END IF;


    -- =========================================================
    -- 4. Order must be payable
    -- =========================================================

    IF v_order.status = 'cancelled' THEN
        RAISE EXCEPTION 'Order is cancelled';
    END IF;


    IF v_order.payment_status = 'paid' THEN
        RAISE EXCEPTION 'Order is already paid';
    END IF;


    IF v_order.payment_status = 'refunded' THEN
        RAISE EXCEPTION 'Order has already been refunded';
    END IF;


    -- =========================================================
    -- 5. Prevent duplicate active payment
    -- =========================================================

    IF EXISTS (
        SELECT 1
        FROM public.payments
        WHERE order_id = v_order.id
          AND status IN ('pending', 'paid')
    ) THEN
        RAISE EXCEPTION 'An active payment already exists for this order';
    END IF;


    -- =========================================================
    -- 6. Create payment
    -- =========================================================

    INSERT INTO public.payments (
        order_id,
        user_id,
        amount,
        gateway,
        status
    )
    VALUES (
        v_order.id,
        v_user_id,
        v_order.total,
        v_gateway,
        'pending'
    )
    RETURNING id
    INTO v_payment_id;


    -- =========================================================
    -- 7. Mark order payment as pending
    -- =========================================================

    UPDATE public.orders
    SET
        payment_status = 'pending',
        updated_at = now()
    WHERE id = v_order.id;


    -- =========================================================
    -- 8. Return payment ID
    -- =========================================================

    RETURN v_payment_id;

END;

$function$;

CREATE OR REPLACE FUNCTION public.fail_order_payment (
  p_payment_id bigint
)
  RETURNS boolean
  LANGUAGE plpgsql
  SECURITY DEFINER
  SET search_path TO 'public'
  AS $function$

DECLARE
    v_payment public.payments%ROWTYPE;
    v_order public.orders%ROWTYPE;
    v_reservation record;
BEGIN

    -- =========================================================
    -- 1. Lock payment
    -- =========================================================

    SELECT *
    INTO v_payment
    FROM public.payments
    WHERE id = p_payment_id
    FOR UPDATE;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'Payment not found';
    END IF;


    -- =========================================================
    -- 2. Lock order
    -- =========================================================

    SELECT *
    INTO v_order
    FROM public.orders
    WHERE id = v_payment.order_id
    FOR UPDATE;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'Order not found';
    END IF;


    -- =========================================================
    -- 3. Already paid?
    -- =========================================================

    IF v_payment.status = 'paid' THEN
        RAISE EXCEPTION 'Payment is already paid';
    END IF;


    -- =========================================================
    -- 4. Already failed?
    -- =========================================================

    IF v_payment.status = 'failed' THEN
        RETURN true;
    END IF;


    -- =========================================================
    -- 5. Payment must be pending
    -- =========================================================

    IF v_payment.status <> 'pending' THEN
        RAISE EXCEPTION 'Payment is not pending';
    END IF;


    -- =========================================================
    -- 6. Mark payment as failed
    -- =========================================================

    UPDATE public.payments
    SET
        status = 'failed'
    WHERE id = p_payment_id;


    -- =========================================================
    -- 7. Release reserved stock
    -- =========================================================

    FOR v_reservation IN
        SELECT
            id,
            product_variant_id,
            quantity
        FROM public.order_stock_reservations
        WHERE order_id = v_payment.order_id
          AND status = 'reserved'
        FOR UPDATE
    LOOP

        UPDATE public.product_variants
        SET stock = stock + v_reservation.quantity
        WHERE id = v_reservation.product_variant_id;


        UPDATE public.order_stock_reservations
        SET
            status = 'released',
            released_at = now()
        WHERE id = v_reservation.id;

    END LOOP;


    -- =========================================================
    -- 8. Update order
    -- =========================================================

    UPDATE public.orders
    SET
        payment_status = 'failed',
        status = 'cancelled',
        updated_at = now()
    WHERE id = v_payment.order_id;


    RETURN true;

END;

$function$;

CREATE OR REPLACE FUNCTION public.handle_new_user()
  RETURNS TRIGGER
  LANGUAGE plpgsql
  SECURITY DEFINER
  SET search_path TO 'public'
  AS $function$
begin
    insert into public.profiles (id)
    values (new.id);

    return new;
end;
$function$;

CREATE OR REPLACE FUNCTION public.is_admin()
  RETURNS boolean
  LANGUAGE sql
  STABLE
  SECURITY DEFINER
  SET search_path TO 'public'
  AS $function$
  SELECT EXISTS (
    SELECT 1
    FROM public.profiles
    WHERE id = auth.uid()
      AND role = 'admin'
  );
$function$;

CREATE OR REPLACE FUNCTION public.validate_promo_code (
  p_code           text,
  p_order_subtotal numeric
)
  RETURNS jsonb
  LANGUAGE plpgsql
  SECURITY DEFINER
  SET search_path TO 'public'
  AS $function$
DECLARE
    v_promo public.promo_codes%ROWTYPE;
    v_discount numeric := 0;
    v_code text;
BEGIN
    v_code := upper(trim(coalesce(p_code, '')));

    IF v_code = '' THEN
        RETURN jsonb_build_object(
            'valid', false,
            'message', 'کد تخفیف را وارد کنید'
        );
    END IF;

    IF p_order_subtotal IS NULL OR p_order_subtotal < 0 THEN
        RETURN jsonb_build_object(
            'valid', false,
            'message', 'مبلغ سفارش نامعتبر است'
        );
    END IF;

    SELECT *
    INTO v_promo
    FROM public.promo_codes
    WHERE upper(trim(code)) = v_code
    LIMIT 1;

    IF NOT FOUND THEN
        RETURN jsonb_build_object(
            'valid', false,
            'message', 'کد تخفیف نامعتبر است'
        );
    END IF;

    IF NOT v_promo.is_active THEN
        RETURN jsonb_build_object(
            'valid', false,
            'message', 'این کد تخفیف فعال نیست'
        );
    END IF;

    IF v_promo.starts_at IS NOT NULL
       AND now() < v_promo.starts_at THEN
        RETURN jsonb_build_object(
            'valid', false,
            'message', 'اعتبار این کد تخفیف هنوز شروع نشده است'
        );
    END IF;

    IF v_promo.expires_at IS NOT NULL
       AND now() > v_promo.expires_at THEN
        RETURN jsonb_build_object(
            'valid', false,
            'message', 'این کد تخفیف منقضی شده است'
        );
    END IF;

    IF v_promo.max_uses IS NOT NULL
       AND v_promo.used_count >= v_promo.max_uses THEN
        RETURN jsonb_build_object(
            'valid', false,
            'message', 'ظرفیت استفاده از این کد تخفیف تکمیل شده است'
        );
    END IF;

    IF p_order_subtotal < v_promo.minimum_order THEN
        RETURN jsonb_build_object(
            'valid', false,
            'message',
            'حداقل مبلغ سفارش برای استفاده از این کد ' ||
            v_promo.minimum_order::text || ' تومان است'
        );
    END IF;

    -- Percentage discount
    IF lower(v_promo.discount_type) = 'percentage' THEN

        IF v_promo.discount_value < 0
           OR v_promo.discount_value > 100 THEN
            RETURN jsonb_build_object(
                'valid', false,
                'message', 'مقدار درصد تخفیف نامعتبر است'
            );
        END IF;

        v_discount :=
            round(
                p_order_subtotal * v_promo.discount_value / 100
            );

    -- Fixed discount
    ELSIF lower(v_promo.discount_type) = 'fixed' THEN

        IF v_promo.discount_value < 0 THEN
            RETURN jsonb_build_object(
                'valid', false,
                'message', 'مقدار تخفیف نامعتبر است'
            );
        END IF;

        v_discount := v_promo.discount_value;

    ELSE

        RETURN jsonb_build_object(
            'valid', false,
            'message', 'نوع تخفیف نامعتبر است'
        );

    END IF;

    -- Never allow discount to exceed subtotal
    v_discount := LEAST(v_discount, p_order_subtotal);

    RETURN jsonb_build_object(
        'valid', true,
        'code', v_promo.code,
        'discount_type', v_promo.discount_type,
        'discount_value', v_promo.discount_value,
        'discount_amount', v_discount,
        'minimum_order', v_promo.minimum_order
    );
END;
$function$;

ALTER TABLE "public"."order_stock_reservations"
  ADD CONSTRAINT "order_stock_reservations_order_fkey" FOREIGN KEY (order_id) REFERENCES public.orders(id) ON DELETE CASCADE;

ALTER TABLE "public"."order_stock_reservations"
  ADD CONSTRAINT "order_stock_reservations_variant_fkey" FOREIGN KEY (product_variant_id) REFERENCES public.product_variants(id) ON DELETE RESTRICT;

ALTER TABLE "public"."orders"
  ADD CONSTRAINT "orders_payment_status_check" CHECK ((payment_status = ANY (ARRAY['unpaid'::text, 'pending'::text, 'paid'::text, 'failed'::text, 'refunded'::text])));

ALTER TABLE "public"."orders"
  ADD CONSTRAINT "orders_status_check" CHECK ((status = ANY (ARRAY['pending'::text, 'confirmed'::text, 'processing'::text, 'shipped'::text, 'delivered'::text, 'cancelled'::text])));

ALTER TABLE "public"."payments"
  ADD CONSTRAINT "payments_order_id_fkey" FOREIGN KEY (order_id) REFERENCES public.orders(id) ON DELETE CASCADE;

ALTER TABLE "public"."profiles"
  ADD CONSTRAINT "profiles_role_check" CHECK ((role = ANY (ARRAY['customer'::text, 'admin'::text])));

CREATE INDEX order_stock_reservations_order_idx ON public.order_stock_reservations USING btree (order_id);

CREATE INDEX order_stock_reservations_status_idx ON public.order_stock_reservations USING btree (status);

CREATE INDEX order_stock_reservations_variant_idx ON public.order_stock_reservations USING btree (product_variant_id);

CREATE INDEX payments_authority_idx ON public.payments USING btree (authority);

CREATE INDEX payments_order_id_idx ON public.payments USING btree (order_id);

CREATE INDEX payments_transaction_id_idx ON public.payments USING btree (transaction_id);

CREATE INDEX payments_user_id_idx ON public.payments USING btree (user_id);

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW
  EXECUTE FUNCTION public.handle_new_user();

CREATE POLICY "Users can add items to their own cart" ON "public"."cart_items"
  FOR INSERT
  TO "authenticated"
  WITH CHECK ((cart_id IN ( SELECT carts.id
   FROM public.carts
  WHERE (carts.user_id = ( SELECT auth.uid() AS uid)))));

CREATE POLICY "Users can delete their own cart items" ON "public"."cart_items"
  FOR DELETE
  TO "authenticated"
  USING ((cart_id IN ( SELECT carts.id
   FROM public.carts
  WHERE (carts.user_id = ( SELECT auth.uid() AS uid)))));

CREATE POLICY "Users can insert their own cart items" ON "public"."cart_items"
  FOR INSERT
  TO "authenticated"
  WITH CHECK ((EXISTS ( SELECT 1
   FROM public.carts
  WHERE ((carts.id = cart_items.cart_id) AND (carts.user_id = auth.uid())))));

CREATE POLICY "Users can update their own cart items" ON "public"."cart_items"
  FOR UPDATE
  TO "authenticated"
  USING ((cart_id IN ( SELECT carts.id
   FROM public.carts
  WHERE (carts.user_id = ( SELECT auth.uid() AS uid)))))
  WITH CHECK ((cart_id IN ( SELECT carts.id
   FROM public.carts
  WHERE (carts.user_id = ( SELECT auth.uid() AS uid)))));

CREATE POLICY "Users can view their own cart items" ON "public"."cart_items"
  FOR SELECT
  TO "authenticated"
  USING ((cart_id IN ( SELECT carts.id
   FROM public.carts
  WHERE (carts.user_id = ( SELECT auth.uid() AS uid)))));

CREATE POLICY "Users can create their own cart" ON "public"."carts"
  FOR INSERT
  TO "authenticated"
  WITH CHECK ((user_id = ( SELECT auth.uid() AS uid)));

CREATE POLICY "Users can create their own carts" ON "public"."carts"
  FOR INSERT
  TO "authenticated"
  WITH CHECK ((auth.uid() = user_id));

CREATE POLICY "Users can delete their own cart" ON "public"."carts"
  FOR DELETE
  TO "authenticated"
  USING ((user_id = ( SELECT auth.uid() AS uid)));

CREATE POLICY "Users can delete their own carts" ON "public"."carts"
  FOR DELETE
  TO "authenticated"
  USING ((auth.uid() = user_id));

CREATE POLICY "Users can update their own cart" ON "public"."carts"
  FOR UPDATE
  TO "authenticated"
  USING ((user_id = ( SELECT auth.uid() AS uid)))
  WITH CHECK ((user_id = ( SELECT auth.uid() AS uid)));

CREATE POLICY "Users can update their own carts" ON "public"."carts"
  FOR UPDATE
  TO "authenticated"
  USING ((auth.uid() = user_id))
  WITH CHECK ((auth.uid() = user_id));

CREATE POLICY "Users can view their own carts" ON "public"."carts"
  FOR SELECT
  TO "authenticated"
  USING ((user_id = ( SELECT auth.uid() AS uid)));

CREATE POLICY "Public can view categories" ON "public"."categories"
  FOR SELECT
  TO "anon", "authenticated"
  USING (true);

CREATE POLICY "Users and admins can view order items" ON "public"."order_items"
  FOR SELECT
  TO "authenticated"
  USING ((EXISTS ( SELECT 1
   FROM public.orders
  WHERE ((orders.id = order_items.order_id) AND ((orders.user_id = ( SELECT auth.uid() AS uid)) OR public.is_admin())))));

CREATE POLICY "Admins can view all stock reservations" ON "public"."order_stock_reservations"
  FOR SELECT
  TO "authenticated"
  USING (public.is_admin());

CREATE POLICY "Users can view their own stock reservations" ON "public"."order_stock_reservations"
  FOR SELECT
  TO "authenticated"
  USING ((EXISTS ( SELECT 1
   FROM public.orders
  WHERE ((orders.id = order_stock_reservations.order_id) AND (orders.user_id = ( SELECT auth.uid() AS uid))))));

CREATE POLICY "Users and admins can view orders" ON "public"."orders"
  FOR SELECT
  TO "authenticated"
  USING (((user_id = ( SELECT auth.uid() AS uid)) OR public.is_admin()));

CREATE POLICY "Admins can view all payments" ON "public"."payments"
  FOR SELECT
  TO "authenticated"
  USING (public.is_admin());

CREATE POLICY "Users can view their own payments" ON "public"."payments"
  FOR SELECT
  TO "authenticated"
  USING ((user_id = ( SELECT auth.uid() AS uid)));

CREATE POLICY "Admins can delete product images" ON "public"."product_images"
  FOR DELETE
  TO "authenticated"
  USING ((EXISTS ( SELECT 1
   FROM public.profiles
  WHERE ((profiles.id = auth.uid()) AND (profiles.role = 'admin'::text)))));

CREATE POLICY "Admins can insert product images" ON "public"."product_images"
  FOR INSERT
  TO "authenticated"
  WITH CHECK ((EXISTS ( SELECT 1
   FROM public.profiles
  WHERE ((profiles.id = auth.uid()) AND (profiles.role = 'admin'::text)))));

CREATE POLICY "Admins can update product images" ON "public"."product_images"
  FOR UPDATE
  TO "authenticated"
  USING ((EXISTS ( SELECT 1
   FROM public.profiles
  WHERE ((profiles.id = auth.uid()) AND (profiles.role = 'admin'::text)))))
  WITH CHECK ((EXISTS ( SELECT 1
   FROM public.profiles
  WHERE ((profiles.id = auth.uid()) AND (profiles.role = 'admin'::text)))));

CREATE POLICY "Public can view product images" ON "public"."product_images"
  FOR SELECT
  TO "anon", "authenticated"
  USING (true);

CREATE POLICY "Admins can delete product variants" ON "public"."product_variants"
  FOR DELETE
  TO "authenticated"
  USING ((EXISTS ( SELECT 1
   FROM public.profiles
  WHERE ((profiles.id = auth.uid()) AND (profiles.role = 'admin'::text)))));

CREATE POLICY "Admins can insert product variants" ON "public"."product_variants"
  FOR INSERT
  TO "authenticated"
  WITH CHECK ((EXISTS ( SELECT 1
   FROM public.profiles
  WHERE ((profiles.id = auth.uid()) AND (profiles.role = 'admin'::text)))));

CREATE POLICY "Admins can update product variants" ON "public"."product_variants"
  FOR UPDATE
  TO "authenticated"
  USING ((EXISTS ( SELECT 1
   FROM public.profiles
  WHERE ((profiles.id = auth.uid()) AND (profiles.role = 'admin'::text)))))
  WITH CHECK ((EXISTS ( SELECT 1
   FROM public.profiles
  WHERE ((profiles.id = auth.uid()) AND (profiles.role = 'admin'::text)))));

CREATE POLICY "Public can view variants" ON "public"."product_variants"
  FOR SELECT
  TO "anon", "authenticated"
  USING (true);

CREATE POLICY "Admins can delete products" ON "public"."products"
  FOR DELETE
  TO "authenticated"
  USING ((EXISTS ( SELECT 1
   FROM public.profiles
  WHERE ((profiles.id = auth.uid()) AND (profiles.role = 'admin'::text)))));

CREATE POLICY "Admins can insert products" ON "public"."products"
  FOR INSERT
  TO "authenticated"
  WITH CHECK ((EXISTS ( SELECT 1
   FROM public.profiles
  WHERE ((profiles.id = auth.uid()) AND (profiles.role = 'admin'::text)))));

CREATE POLICY "Admins can update products" ON "public"."products"
  FOR UPDATE
  TO "authenticated"
  USING ((EXISTS ( SELECT 1
   FROM public.profiles
  WHERE ((profiles.id = auth.uid()) AND (profiles.role = 'admin'::text)))))
  WITH CHECK ((EXISTS ( SELECT 1
   FROM public.profiles
  WHERE ((profiles.id = auth.uid()) AND (profiles.role = 'admin'::text)))));

CREATE POLICY "Admins can view all products" ON "public"."products"
  FOR SELECT
  TO "authenticated"
  USING ((EXISTS ( SELECT 1
   FROM public.profiles
  WHERE ((profiles.id = auth.uid()) AND (profiles.role = 'admin'::text)))));

CREATE POLICY "Public can view active products" ON "public"."products"
  FOR SELECT
  TO "anon", "authenticated"
  USING ((is_active = true));

CREATE POLICY "Users can update their own profile" ON "public"."profiles"
  FOR UPDATE
  TO "authenticated"
  USING ((auth.uid() = id))
  WITH CHECK ((auth.uid() = id));

CREATE POLICY "Users can view their own profile" ON "public"."profiles"
  FOR SELECT
  TO "authenticated"
  USING ((auth.uid() = id));

CREATE POLICY "Admins can delete product image objects" ON "storage"."objects"
  FOR DELETE
  TO "authenticated"
  USING (((bucket_id = 'product-images'::text) AND (EXISTS ( SELECT 1
   FROM public.profiles
  WHERE ((profiles.id = auth.uid()) AND (profiles.role = 'admin'::text))))));

CREATE POLICY "Admins can update product image objects" ON "storage"."objects"
  FOR UPDATE
  TO "authenticated"
  USING (((bucket_id = 'product-images'::text) AND (EXISTS ( SELECT 1
   FROM public.profiles
  WHERE ((profiles.id = auth.uid()) AND (profiles.role = 'admin'::text))))))
  WITH CHECK (((bucket_id = 'product-images'::text) AND (EXISTS ( SELECT 1
   FROM public.profiles
  WHERE ((profiles.id = auth.uid()) AND (profiles.role = 'admin'::text))))));

CREATE POLICY "Admins can upload product images" ON "storage"."objects"
  FOR INSERT
  TO "authenticated"
  WITH CHECK (((bucket_id = 'product-images'::text) AND (EXISTS ( SELECT 1
   FROM public.profiles
  WHERE ((profiles.id = auth.uid()) AND (profiles.role = 'admin'::text))))));

REVOKE ALL ON FUNCTION "public"."admin_update_order_status"(bigint, text) FROM PUBLIC;

GRANT EXECUTE ON FUNCTION "public"."admin_update_order_status"(bigint, text) TO "authenticated", "postgres", "service_role";

REVOKE ALL ON FUNCTION "public"."confirm_order_payment"(bigint) FROM PUBLIC;

GRANT EXECUTE ON FUNCTION "public"."confirm_order_payment"(bigint) TO "postgres", "service_role";

REVOKE ALL ON FUNCTION "public"."create_order"(text, text, text) FROM PUBLIC;

GRANT EXECUTE ON FUNCTION "public"."create_order"(text, text, text) TO "postgres", "service_role";

REVOKE ALL ON FUNCTION "public"."create_order_from_cart"(text, text, text, text, numeric, numeric) FROM PUBLIC;

GRANT EXECUTE ON FUNCTION "public"."create_order_from_cart"(text, text, text, text, numeric, numeric) TO "authenticated", "postgres", "service_role";

REVOKE ALL ON FUNCTION "public"."create_payment"(bigint, text) FROM PUBLIC;

GRANT EXECUTE ON FUNCTION "public"."create_payment"(bigint, text) TO "authenticated", "postgres", "service_role";

REVOKE ALL ON FUNCTION "public"."fail_order_payment"(bigint) FROM PUBLIC;

GRANT EXECUTE ON FUNCTION "public"."fail_order_payment"(bigint) TO "postgres", "service_role";

GRANT EXECUTE ON FUNCTION "public"."handle_new_user"() TO PUBLIC, "anon", "authenticated", "postgres", "service_role";

REVOKE ALL ON FUNCTION "public"."is_admin"() FROM PUBLIC;

GRANT EXECUTE ON FUNCTION "public"."is_admin"() TO "anon", "authenticated", "postgres", "service_role";

REVOKE ALL ON FUNCTION "public"."validate_promo_code"(text, numeric) FROM PUBLIC;

GRANT EXECUTE ON FUNCTION "public"."validate_promo_code"(text, numeric) TO "anon", "authenticated", "postgres", "service_role";

REVOKE ALL ON TABLE "public"."order_stock_reservations" FROM "authenticated";

GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER ON TABLE "public"."order_stock_reservations" TO "authenticated";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."order_stock_reservations" TO "postgres", "service_role";

REVOKE ALL ON TABLE "public"."payments" FROM "authenticated";

GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER ON TABLE "public"."payments" TO "authenticated";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."payments" TO "postgres", "service_role";
